//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.dreamsyssoft.aarestdemo.rest.java.util;

import java.util.ArrayList;
import com.dreamsyssoft.aarestdemo.model.User;

public class List_User
    extends ArrayList<User>
{


}
